name: pytrance
channels:
  - conda-forge
dependencies:
  - pip>=24.2
  - python>=3.9,<3.13

  - pip:
      - igraph
      - ipykernel
      - leidenalg
      - scanpy>=1.10.3
      - shapely>=2.0
      - tensorboard>=2.20
      - torch-geometric>=2.6
      
